### ISSUE TITLE
Hyperlane Warp Routes created for Taiko token

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#19548]
deployment.yaml:

```yaml
bsc:
  interchainSecurityModule:
    modules:
      - relayer: "0x75452338e6938507351578D208BD300A92Fb80CD"
        type: trustedRelayerIsm
      - domains: {}
        owner: "0x75452338e6938507351578D208BD300A92Fb80CD"
        type: defaultFallbackRoutingIsm
    threshold: 1
    type: staticAggregationIsm
  owner: "0x75452338e6938507351578D208BD300A92Fb80CD"
  type: synthetic
ethereum:
  interchainSecurityModule:
    modules:
      - relayer: "0x75452338e6938507351578D208BD300A92Fb80CD"
        type: trustedRelayerIsm
      - domains: {}
        owner: "0x75452338e6938507351578D208BD300A92Fb80CD"
        type: defaultFallbackRoutingIsm
    threshold: 1
    type: staticAggregationIsm
  owner: "0x75452338e6938507351578D208BD300A92Fb80CD"
  token: "0x10dea67478c5F8C5E2D90e5E9B26dBe60c54d800"
  type: collateral
taiko:
  interchainSecurityModule:
    modules:
      - relayer: "0x75452338e6938507351578D208BD300A92Fb80CD"
        type: trustedRelayerIsm
      - domains: {}
        owner: "0x75452338e6938507351578D208BD300A92Fb80CD"
        type: defaultFallbackRoutingIsm
    threshold: 1
    type: staticAggregationIsm
  owner: "0x75452338e6938507351578D208BD300A92Fb80CD"
  token: "0xA9d23408b9bA935c230493c40C73824Df71A0975"
  type: collateral
```

bsc-ethereum-taiko-config.yaml:

```yaml
# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x993Bc153fFbC484D2f78210d02dC26Dd75B0fC1d"
    chainName: bsc
    connections:
      - token: ethereum|ethereum|0x53929c99E006fe62A8c9d1B8AA02618Dc3Fd40cA
      - token: ethereum|taiko|0x993Bc153fFbC484D2f78210d02dC26Dd75B0fC1d
    decimals: 18
    name: Taiko Token
    standard: EvmHypSynthetic
    symbol: TAIKO
  - addressOrDenom: "0x53929c99E006fe62A8c9d1B8AA02618Dc3Fd40cA"
    chainName: ethereum
    collateralAddressOrDenom: "0x10dea67478c5F8C5E2D90e5E9B26dBe60c54d800"
    connections:
      - token: ethereum|bsc|0x993Bc153fFbC484D2f78210d02dC26Dd75B0fC1d
      - token: ethereum|taiko|0x993Bc153fFbC484D2f78210d02dC26Dd75B0fC1d
    decimals: 18
    name: Taiko Token
    standard: EvmHypCollateral
    symbol: TAIKO
  - addressOrDenom: "0x993Bc153fFbC484D2f78210d02dC26Dd75B0fC1d"
    chainName: taiko
    collateralAddressOrDenom: "0xA9d23408b9bA935c230493c40C73824Df71A0975"
    connections:
      - token: ethereum|bsc|0x993Bc153fFbC484D2f78210d02dC26Dd75B0fC1d
      - token: ethereum|ethereum|0x53929c99E006fe62A8c9d1B8AA02618Dc3Fd40cA
    decimals: 18
    name: Taiko Token
    standard: EvmHypCollateral
    symbol: TAIKO
```

**Comment by dantaik** [comment]
TODO: 

- [ ] figure out if we need to somehow add these two files to Hyperlane's repo
- [ ] change owner address from `0x75452338e6938507351578D208BD300A92Fb80CD` to `controller.taiko.eth`

**Comment by dantaik** [comment]
Additial logs from the cli:


```
Done adding warp route at filesystem registry
    tokens:
      - chainName: bsc
        standard: EvmHypSynthetic
        decimals: 18
        symbol: TAIKO
        name: Taiko Token
        addressOrDenom: "0x993Bc153fFbC484D2f78210d02dC26Dd75B0fC1d"
        connections:
          - token: ethereum|ethereum|0x53929c99E006fe62A8c9d1B8AA02618Dc3Fd40cA
          - token: ethereum|taiko|0x993Bc153fFbC484D2f78210d02dC26Dd75B0fC1d
      - chainName: ethereum
        standard: EvmHypCollateral
        decimals: 18
        symbol: TAIKO
        name: Taiko Token
        addressOrDenom: "0x53929c99E006fe62A8c9d1B8AA02618Dc3Fd40cA"
        collateralAddressOrDenom: "0x10dea67478c5F8C5E2D90e5E9B26dBe60c54d800"
        connections:
          - token: ethereum|bsc|0x993Bc153fFbC484D2f78210d02dC26Dd75B0fC1d
          - token: ethereum|taiko|0x993Bc153fFbC484D2f78210d02dC26Dd75B0fC1d
      - chainName: taiko
        standard: EvmHypCollateral
        decimals: 18
        symbol: TAIKO
        name: Taiko Token
        addressOrDenom: "0x993Bc153fFbC484D2f78210d02dC26Dd75B0fC1d"
        collateralAddressOrDenom: "0xA9d23408b9bA935c230493c40C73824Df71A0975"
        connections:
          - token: ethereum|bsc|0x993Bc153fFbC484D2f78210d02dC26Dd75B0fC1d
          - token: ethereum|ethereum|0x53929c99E006fe62A8c9d1B8AA02618Dc3Fd40cA
```
